### ISSUE TITLE
Configure LOG_FORMAT

### ISSUE THREAD

**Issue by AlainDeleglise** [grafana/flagger-k6-webhook#219]
Hi,

I'm using the latest chart version and the latest image. 
I'm trying to output logs in JSON format using the env var, as described here https://grafana.com/docs/k6/latest/using-k6/k6-options/reference/#logformat

I'm using this code in the helm chart values :

```
    webhook:
      name: "k6-loadtester"
      vars:
        "KUBERNETES_CLIENT": "in-cluster"
        "K6_LOG_FORMAT": "json"
```

But the logs are still in RAW format. 

Am I missing something?
